### ISSUE TITLE
Clarification

### ISSUE THREAD

**Issue by Blackweda** [maseev/alpaca-trade-api-java#1]
Is this meant to be run on an Android device or laptop?

I'm trying to get api that works on mobile and combine with my own logic.

**Comment by maseev** [comment]
I've never tried this library on an Android device myself, but I think there won't be any problems with that.

This library uses Java 1.8 and [AHC](https://github.com/AsyncHttpClient/async-http-client) which uses [Netty](https://github.com/netty/netty) under the hood. If I'm not mistaken, both Java 1.8 and Netty are available on Android. 

So give it a try. Something tells me that it should be pretty straightforward to run an app that uses this library on an Android device.

**Comment by Blackweda** [comment]
Awesome thanks.. will give it a go
